name: Build and publish changed Docker image
description: Build and publish Docker images based on changed paths
author: dawidd6
branding:
  icon: anchor
  color: blue
inputs:
  github_token:
    description: Github token
    required: false
  docker_username:
    description: DockerHub username
    required: false
  docker_password:
    description: DockerHub password
    required: false
runs:
  using: docker
  image: Dockerfile