name: Build and publish multi platform Docker images
description: Build and publish multi platform Docker images based on changed paths from pushed commits
author: dawidd6
branding:
  icon: anchor
  color: blue
inputs:
  token:
    description: GitHub token
    required: true
    default: ${{github.token}}
  registry:
    description: Registry url
    required: true
    default: docker.io
  username:
    description: Registry username
    required: false
  password:
    description: Registry password
    required: false
  platforms:
    description: Platforms for which the image will be built (comma separated)
    required: true
    default: linux/amd64
  tag:
    description: Image tag
    required: true
    default: latest
runs:
  using: node12
  main: main.js