name: Build and publish changed Docker image
description: Build and publish Docker images based on changed paths
author: dawidd6
branding:
  icon: anchor
  color: blue
inputs:
  github_token:
    description: Github token
    required: false
  docker_username:
    description: DockerHub username
    required: false
  docker_password:
    description: DockerHub password
    required: false
  platforms:
    description: Platforms for which the image will be built (comma separated)
    required: false
    default: linux/amd64
  tag:
    description: Image tag
    required: false
    default: latest
runs:
  using: docker
  image: Dockerfile