name: Test action

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        uses: ./
        with:
          entrypoint: /test.rb
      - name: Run
        uses: ./
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          docker_username: ${{secrets.DOCKER_USERNAME}}
          docker_password: ${{secrets.DOCKER_PASSWORD}}