name: Test Action (push)

on:
  push:
    branches:
      - master

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        uses: ./
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6
